{% set name = "pyjanitor" %}
{% set version = "0.31.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-devs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8c05f9687ebdf8428c71a9c80d5da8a5c1c77bddf6067dbf5c38036ffd15be5a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - natsort
    - pandas-flavor
    - multipledispatch
    - scipy
    - xarray

test:
  imports:
    - janitor
    - janitor.accessors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyjanitor-devs/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  description: Tools for cleaning pandas DataFrames
  doc_url: https://pyjanitor.readthedocs.io
  dev_url: https://github.com/pyjanitor-devs/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
    - ocefpaf
