{% set name = "pyjanitor" %}
{% set version = "0.32.23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}-devs/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e7c6ac87268fa03b7c7a2988a4adf4260be80c0c8f6f5badfd2e10c2e8254c3a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # ModuleNotFoundError: No module named 'pandas.core.col'
  # Unable to use pandas>3 with py310
  skip: true  # [py<311]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61.0
  run:
    - python
    - natsort >=8.4.0,<9
    - pandas-flavor >=0.8.1,<0.9
    - multipledispatch
    - scipy
    - janitor-rs >=0.6.1,<0.7

  run_constrained:
    - isort >=4.3.18
    - ipython >7.31.1

test:
  imports:
    - janitor
    - janitor.accessors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyjanitor-devs/pyjanitor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for cleaning pandas DataFrames
  description: Tools for cleaning pandas DataFrames
  doc_url: http://pyjanitor.readthedocs.io
  dev_url: https://github.com/pyjanitor-devs/pyjanitor

extra:
  recipe-maintainers:
    - ericmjl
    - ocefpaf
